# Generated by Django 5.0.6 on 2024-05-15 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Fuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FuelStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='station/')),
                ('closing_time', models.TimeField()),
                ('opening_time', models.TimeField()),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('avaliable_fuels', models.ManyToManyField(blank=True, to='main.fuel')),
                ('category', models.ManyToManyField(blank=True, to='main.category')),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('fuel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.fuel')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.fuelstation')),
            ],
        ),
    ]
